### ISSUE TITLE
Mamba environment update fails with latest mambaforge image

### ISSUE THREAD

**Issue by cjproud** [conda-forge/miniforge-images#62]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With the latest mambaforge image my environment update fails during a docker container build, rolling back to 4.12.0-2 allows a successful environment update. The `conda list` and `conda info` info is from the environment within the docker container. Here is the log below:

```
#0 104.6 # To activate this environment, use
#0 104.6 #
#0 104.6 #     $ conda activate base
#0 104.6 #
#0 104.6 # To deactivate an active environment, use
#0 104.6 #
#0 104.6 #     $ conda deactivate
#0 104.6 
#0 104.6 Retrieving notices: ...working... failed
#0 104.6 Traceback (most recent call last):
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1125, in __call__
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda_env/cli/main.py", line 80, in do_call
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/core.py", line 75, in wrapper
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/core.py", line 39, in display_notices
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/http.py", line 36, in get_notice_responses
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/http.py", line 39, in <genexpr>
#0 104.6   File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
#0 104.6   File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
#0 104.6   File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
#0 104.6   File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
#0 104.6   File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/http.py", line 42, in <lambda>
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/cache.py", line 37, in wrapper
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 460, in send
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 263, in cert_verify
#0 104.6 OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem
#0 104.6 
#0 104.6 During handling of the above exception, another exception occurred:
#0 104.6 
#0 104.6 Traceback (most recent call last):
#0 104.6   File "/opt/conda/bin/conda-env", line 7, in <module>
#0 104.6     sys.exit(main())
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda_env/cli/main.py", line 91, in main
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1413, in conda_exception_handler
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1128, in __call__
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1170, in handle_exception
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1181, in handle_unexpected_exception
#0 104.6   File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1251, in print_unexpected_error_report
#0 104.6 ModuleNotFoundError: No module named 'conda.cli.main_info'
------
failed to solve: executor failed running [/bin/sh -c conda env update --name base --file environment_dev.yml]: exit code: 1
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
asgiref                   3.5.2              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0                   pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
binutils_impl_linux-aarch64 2.36.1               h026399b_2    conda-forge
brotli                    1.0.9                h4e544f5_7    conda-forge
brotli-bin                1.0.9                h4e544f5_7    conda-forge
brotlipy                  0.7.0           py39h0fd3b05_1004    conda-forge
bzip2                     1.0.8                hf897c2e_4    conda-forge
c-ares                    1.18.1               hf897c2e_0    conda-forge
ca-certificates           2022.5.18.1          h4fd8a4c_0    conda-forge
certifi                   2022.5.18.1      py39h4420490_0    conda-forge
cffi                      1.15.0           py39hab139ec_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39h4420490_0    conda-forge
conda-package-handling    1.8.1            py39h0fd3b05_1    conda-forge
constantly                15.1.0                   pypi_0    pypi
cryptography              37.0.2           py39h32042e6_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
django                    4.0.6            py39ha65689a_0    conda-forge
django-debug-toolbar      3.6.0                    pypi_0    pypi
django-debug-toolbar-line-profiling 0.7.3                    pypi_0    pypi
django-debug-toolbar-template-profiler 2.1.0                    pypi_0    pypi
django-login-required-middleware 0.8.0                    pypi_0    pypi
django-redis              5.2.0                    pypi_0    pypi
et_xmlfile                1.0.1                   py_1001    conda-forge
fire                      0.4.0                    pypi_0    pypi
fonttools                 4.37.1           py39h0fd3b05_0    conda-forge
freetype                  2.12.1               hbbbf32d_0    conda-forge
gcc                       12.1.0              h75b0f6e_10    conda-forge
gcc_impl_linux-aarch64    12.1.0              h9c21524_16    conda-forge
gevent                    21.12.0          py39hd5adbdb_2    conda-forge
gfortran                  12.1.0              hbe045d2_10    conda-forge
gfortran_impl_linux-aarch64 12.1.0              hd36f8f4_16    conda-forge
greenlet                  1.1.3            py39h3d8bfb9_0    conda-forge
gunicorn                  20.1.0           py39h4420490_2    conda-forge
gxx                       12.1.0              h75b0f6e_10    conda-forge
gxx_impl_linux-aarch64    12.1.0              h9c21524_16    conda-forge
h2                        4.1.0                    pypi_0    pypi
hiredis                   2.0.0                    pypi_0    pypi
hpack                     4.0.0                    pypi_0    pypi
hyperframe                6.0.1                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
icu                       70.1                 ha18d298_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39ha65689a_0    conda-forge
incremental               21.3.0                   pypi_0    pypi
jill                      0.11.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h9cdd2b7_2    conda-forge
jsonschema                4.15.0                   pypi_0    pypi
julia                     0.5.7                    pypi_0    pypi
kernel-headers_linux-aarch64 4.18.0              h5b4a56d_13    conda-forge
keyutils                  1.6.1                h4e544f5_0    conda-forge
kiwisolver                1.4.4            py39h110580c_0    conda-forge
krb5                      1.19.3               h7c456eb_0    conda-forge
lcms2                     2.12                 h012adcb_0    conda-forge
ld_impl_linux-aarch64     2.36.1               h02ad14f_2    conda-forge
lerc                      4.0.0                h4de3ea5_0    conda-forge
libarchive                3.5.2                h610d84a_2    conda-forge
libblas                   3.9.0           16_linuxaarch64_openblas    conda-forge
libbrotlicommon           1.0.9                h4e544f5_7    conda-forge
libbrotlidec              1.0.9                h4e544f5_7    conda-forge
libbrotlienc              1.0.9                h4e544f5_7    conda-forge
libcblas                  3.9.0           16_linuxaarch64_openblas    conda-forge
libcurl                   7.83.1               h8fd98b7_0    conda-forge
libdeflate                1.13                 h4e544f5_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc-devel_linux-aarch64 12.1.0              hf2ffb8d_16    conda-forge
libgcc-ng                 12.1.0              h3242a24_16    conda-forge
libgfortran-ng            12.1.0              he9431aa_16    conda-forge
libgfortran5              12.1.0              h41d5c85_16    conda-forge
libgomp                   12.1.0              h3242a24_16    conda-forge
libiconv                  1.16                 h6dd45c4_0    conda-forge
liblapack                 3.9.0           16_linuxaarch64_openblas    conda-forge
libmamba                  0.22.1               h8683862_1    conda-forge
libmambapy                0.22.1           py39hdaab871_1    conda-forge
libnghttp2                1.47.0               h75cb1c7_0    conda-forge
libnsl                    2.0.0                hf897c2e_0    conda-forge
libopenblas               0.3.21          pthreads_h6cb6f83_3    conda-forge
libpng                    1.6.37               hf9034f9_4    conda-forge
libsanitizer              12.1.0              hd01590b_16    conda-forge
libsolv                   0.7.22               h7866ba4_0    conda-forge
libssh2                   1.10.0               h1ab2c7b_2    conda-forge
libstdcxx-devel_linux-aarch64 12.1.0              hf2ffb8d_16    conda-forge
libstdcxx-ng              12.1.0              hd01590b_16    conda-forge
libtiff                   4.4.0                hb3f8b40_3    conda-forge
libuuid                   2.32.1            hf897c2e_1000    conda-forge
libuv                     1.44.2               h4e544f5_0    conda-forge
libwebp-base              1.2.4                h4e544f5_0    conda-forge
libxcb                    1.13              h3557bc0_1004    conda-forge
libxml2                   2.9.14               h370961a_0    conda-forge
libzlib                   1.2.12               h4e544f5_0    conda-forge
line-profiler             3.5.1                    pypi_0    pypi
lz4-c                     1.9.3                h01db608_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  h309ac5b_1    conda-forge
mamba                     0.22.1           py39hc9db4b5_1    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3            py39ha65689a_2    conda-forge
matplotlib-base           3.5.3            py39h149fffc_2    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.29               hcde889d_1    conda-forge
mysql-libs                8.0.29               h913e832_1    conda-forge
mysqlclient               2.0.3            py39h3d8bfb9_3    conda-forge
ncurses                   6.3                  headf329_1    conda-forge
numpy                     1.23.2           py39h7190128_0    conda-forge
openjpeg                  2.5.0                h9b6de37_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1o               h4e544f5_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py39h63591b6_0    conda-forge
pillow                    9.2.0            py39hf18909c_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
priority                  1.3.0                    pypi_0    pypi
pthread-stubs             0.4               hb9de7d4_1001    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39h0fd3b05_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyexcelerate              0.10.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1            py39ha65689a_5    conda-forge
python                    3.9.9           hc23e7ad_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-gnupg              0.5.0                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h0fd3b05_4    conda-forge
readline                  8.1                  h1a49cc3_0    conda-forge
redis-py                  4.3.4              pyhd8ed1ab_0    conda-forge
reproc                    14.2.3               hf897c2e_0    conda-forge
reproc-cpp                14.2.3               h01db608_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-futures          1.0.0                    pypi_0    pypi
ruamel_yaml               0.15.80         py39h0fd3b05_1007    conda-forge
semantic-version          2.10.0                   pypi_0    pypi
service-identity          21.1.0                   pypi_0    pypi
setuptools                62.3.2           py39ha65689a_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               hc74f5b8_0    conda-forge
sqlparse                  0.4.2              pyhd8ed1ab_0    conda-forge
sysroot_linux-aarch64     2.17                h43d7e78_13    conda-forge
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.12               hd8af866_0    conda-forge
tornado                   6.2              py39hb9a1dbb_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
twisted                   22.4.0                   pypi_0    pypi
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39h0fd3b05_1    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wget                      3.2                      pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1           py39h0fd3b05_0    conda-forge
xorg-libxau               1.0.9                h3557bc0_0    conda-forge
xorg-libxdmcp             1.1.3                h3557bc0_0    conda-forge
xz                        5.2.5                h6dd45c4_1    conda-forge
yaml                      0.2.5                hf897c2e_2    conda-forge
yaml-cpp                  0.6.3                h54f1f3f_4    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h4e544f5_0    conda-forge
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0            py39hb9a1dbb_2    conda-forge
zstd                      1.5.2                haad177d_1    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __linux=5.10.104=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=aarch64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-aarch64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.9 Linux/5.10.104-linuxkit ubuntu/20.04.4 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by raybellwaves** [comment]
also seeing this

**Comment by raybellwaves** [comment]
more info here: https://github.com/conda-forge/miniforge/issues/350

**Comment by cjproud** [comment]
Cheers @raybellwaves. Updating my conda environment to use python=3.10 fixed this issue.
